language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "variables-preview-overlay:${TRAVIS_BRANCH}"
  --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: jnhkilgVZ5jTRQbEGdJLe5LMHz5vJAgUNENHJ/z04aPk3lsGoFeaGgk+LZhh8hme+9qszNbpzixKAx53AQEfI1DiGHyIoXepgFel2n40Q4CQcLPmrBqJrZOzky5VBgv2CRuR/sJXTjxt5MhrYeBqgC55fYVepNgioQMl4H2ttfW1kw64uXSGPHrZhCwgqllXDjvKtoCJk6wA/ZNlz4pL/94zvCp/GlERn2jZlm7ELvny4+W0Tp2h9+uoX1c/O8asny6wD39Zh4XFDpD81dkZSx79dpLk2tCoqhSnx9nDP178z6WjhkUqNkW2/vXmLL2wh67DEinNUhL5JH0b1QLJi9/IU+//kkah8p1vWE18WSWZWQX0KNbheFlTKHRJhwDGrEiSPFanHyTqXDRRK6vpAs1ivaqN6YJaJLWK5NU99lZkhm0JWCFnIJJqsJg2vN+1qa4mxGyJPIkhdf9aK16uMATBtK7K+3aRFvb5n0LibycTYgd/2oFxFRZQqmHJYf5Y/EXqCEr/gwYXvc6SHP2ffiWLncyQsM5I8XcGjFpSjrwtdLXIfVYJQ/3nI+Y/Q43T+iXCIMcyfhGcEZcXzBK7V5MHXeSDTUokNNhKlmUV3Z/wRkgQ34V2fo7zWrnbmimeLL71BMkJtk5AfPLZtSFtDInMUazKq9x0kmawFe34e1U=
  - secure: NLthRJxwHCIe2CFfuJAzRnqok6GJR4gSN1v98YovAZLham5DTXaGrYb4UDnQqekTni+hxNIBmO/aE8dh7fR1rk6a6LTJYw9y1XgdA2mq+3+hJ+7rOo8aM34y0HhsELd0636CCIbNg2ShX7s3/luqCmWHzzAmLxZiw1P+cT0f+lnvdxSc3fkNv5uAmT+LpbgcR8weODX7WUZ4sBfJUn3Cp78B+4E4dZ7IFSix/kydayH1mjnJeszLPpwIyMPfomeZXB/D0k7kABElXQMdkSUxKaQ2CLxDrmM3arTNJQRItgUSQoUq0bD++0OcC++IMk3Ujn0sOg1o/it2IJq1pnBawS6TFqkMNd6/gdel8AOWnxaptUOUOhGzKnooVCrnsLhP4Xc2GyL+h1PB5LsCHyjVj8aCtYetMypxRlCMCmhfL5Zmc1oU1B1MEhAn8D/x+VmMGNc5AEG+/iylq+F9YmnfvH4pUoqCNIwZEaP47K0hT/BJq+6leFe804bosGybKyX6IPyGH/BfBLTbw9XU3+ztoSnun80wtICk49lAZcoKCXC6tWYo2hEdy9g2Lc/vQM6w5tgZwmYQtRiseGjDT5l+OKZY+Z/SsJtfntysO9lA7sAOoYMexDio7BZwg1eycxlL7pK94Eb4TCgZydtO36f7kQS+E17PcFQpoECSfcmSEXk=
